openapi: "3.1.0"
info:
  title: Library management API
  version: "1.0.0"
servers:
  - url: https://localhost
paths:
  /books:
    get:
      operationId: getAll
      tags:
        - Books
      summary: get all books available
      parameters:
        - $ref: "#/components/parameters/bookName"
        - $ref: "#/components/parameters/releaseDate"
      responses:
        200:
          description: list of all books or of a filtered book
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/book"
        400:
          description: Invalid input data.

    put:
      operationId: delete
      tags:
        - Books
      summary: Update or create a book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrupdateBook'
      responses:
        200:
          description: Book updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        201:
          description: Book created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        400:
          description: Invalid input data.

    post:
      operationId: addBook
      tags:
        - Books
      summary: add a new book
      requestBody:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/book"
      responses:
        200:
          description: book created with success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/book"
        400:
          description: Invalid input data.
  /books/{bookId}/authors/{authorId} :
    put:
      operationId: updateBookAuthor
      tags:
        - Books
      summary: update book's author
      parameters:
        - $ref: "#/components/parameters/bookId"
        - $ref: "#/components/parameters/authorId"
      responses:
        200:
          description: book's author updated with success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/book"

  /book/delete/{bookId}:
    delete:
      operationId: delete
      tags:
        - Books
      summary: delete a book
      parameters:
        - $ref: "#/components/parameters/bookId"
      responses:
        200:
          description: book deleted with success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/book"
        400:
          description: Invalid input data.

  /authors:
    get:
      operationId: getAll
      tags:
        - Authors
      summary: get all books authors
      parameters:
        - $ref: "#/components/parameters/authorName"
      responses:
        200:
          description: list of all authors or of a filtered author
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/author"
        400:
          description: Invalid input data.

  /author/add:
    post:
      operationId: add
      tags:
        - Authors
      summary: add a new author
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/author"
      responses:
        200:
          description: author added with success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/author"
        400:
          description: Invalid input data.

  /author/update/{authorId}:
    put:
      operationId: update
      tags:
        - Authors
      summary: update a author
      parameters:
        - $ref: "#/components/parameters/authorId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/author'
      responses:
        '200':
          description: author updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/author'
        '201':
          description: author added successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/author'
        400:
          description: Invalid input data.

  /author/delete/{authorId}:
    delete:
      operationId: delete
      tags:
        - Authors
      summary: delete an author
      parameters:
        - $ref: "#/components/parameters/authorId"
      responses:
        200:
          description: author deleted with success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/author"
        400:
          description: Invalid input data.

components:
  parameters:
    bookName:
      in: query
      name: bookName
      required: false
      schema:
        type: string
        example: The mathematical principle of natural philosophy
        description: Title of the book
    bookId:
      in: path
      name: bookId
      required: true
      schema:
        type: string
        example: bk-sc1-phys-028
    authorId:
      in: path
      name: authorId
      required: true
      schema:
        type: string
        example: auth-sc1-028
    authorName:
      in: query
      name: authorName
      required: false
      schema:
        type: string
        example: Isaac Newton
        description: Name of a book's author
    releaseDate:
        name: releaseDate
        in: query
        description: Start and end of release date interval (two values allowed)
        required: false
        schema:
          type: string
          pattern: ^\d{4}-\d{2}-\d{2};\d{4}-\d{2}-\d{2}$
          example : 1710-11-12;1740-09-30
  schemas:
    author:
      type: object
      properties:
        ID:
          type: string
          example: auth-sc1-028
          nullable: false
        Name:
          type: string
          example: Isaac NEWTON
        Sex:
          type: string
          enum: [M, F]
    book:
      type: object
      allOf:
        - $ref: "#/components/schemas/CrupdateBook"
        - properties:
            author:
              allOf:
                - $ref: "#/components/schemas/author"
    CrupdateBook:
      properties:
        ID:
          type: string
          example: bk-sc1-phys-028
        bookName:
          type: string
          example: The mathematical principle of natural philosophy
        pageNumbers:
          type: integer
          format: int32
          example: 512
        topic:
          type: string
          enum: [ ROMANCE, COMEDY, OTHER ]
        releaseDate:
          type: string
          format: date